CREATE TABLE EMP1(EMPID INT, EMPNAME CHAR(10), LOCATION CHAR(10))

SELECT * FROM EMP1

-- input procedure
CREATE PROCEDURE 
PRO_EMP_1 @EMPID INT, @EMPNAME CHAR(10), @EMPLOCATION CHAR(10)
AS 
BEGIN
INSERT INTO EMP1 VALUES (@EMPID, @EMPNAME, @EMPLOCATION)
END

EXECUTE PRO_EMP_1 101, 'NATASHA', 200

SELECT * FROM EMP1;
